// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	ping "github.com/LXJ0000/go-kitex/app/gateway/biz/router/ping"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	ping.Register(r)
}
