version: '3'
services:
  mysql:
    image: 'mysql:8.0.19'
    ports:
      - 13306:3306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  redis:
    image: 'redis:7.0.0'
    ports:
      - 16379:6379
